import { Router } from "express";
import { requireAuth, requireRole } from "../auth/auth.middleware.js";
import * as controller from "./devices.controller.js";
const router=Router();
router.get("/",requireAuth,requireRole("ADMIN","MANAGER"),controller.list);
router.get("/:id/recent-punches",requireAuth,requireRole("ADMIN","MANAGER"),controller.recent);
router.patch("/punches/ignore",requireAuth,requireRole("ADMIN"),controller.ignorePunches);
router.delete("/punches",requireAuth,requireRole("ADMIN"),controller.deletePunches);
router.post("/punches/reprocess",requireAuth,requireRole("ADMIN"),controller.reprocessPunches);
router.post("/punches/clear-date",requireAuth,requireRole("ADMIN"),controller.clearTestPunches);
router.get("/:id",requireAuth,requireRole("ADMIN","MANAGER"),controller.get);
router.post("/",requireAuth,requireRole("ADMIN"),controller.create);
router.patch("/:id",requireAuth,requireRole("ADMIN"),controller.update);
router.patch("/:id/activate",requireAuth,requireRole("ADMIN"),controller.activate);
router.patch("/:id/deactivate",requireAuth,requireRole("ADMIN"),controller.deactivate);
export default router;
