import crypto from "node:crypto";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { getDatabasePool } from "../src/infrastructure/database/database.js";
import { attendanceSchedulerStarted, evaluateCurrentAttendanceStatuses, startAttendanceStatusScheduler, stopAttendanceStatusScheduler } from "../src/modules/attendance/attendance-scheduler.service.js";

const pool=getDatabasePool(); const marker=`scheduler-${crypto.randomUUID()}`; const day="2993-07-10"; let shift="",employee=""; const bio=crypto.randomInt(700000000,790000000);
const at=(time:string)=>new Date(`${day}T${time}+05:30`);
async function evaluate(time:string){const value=at(time);process.env.ATTENDANCE_TEST_NOW=value.toISOString();return evaluateCurrentAttendanceStatuses(value);}
async function status(){return (await pool.query("SELECT status,note,late_minutes,working_minutes,punch_in_at,punch_out_at FROM daily_attendance_records WHERE employee_id=$1 AND attendance_date=$2",[employee,day])).rows[0];}
async function clear(){await pool.query("DELETE FROM daily_attendance_records WHERE employee_id=$1",[employee]);await pool.query("DELETE FROM raw_attendance_punches WHERE source_event_key LIKE $1",[`${marker}%`]);}
async function punch(time:string,key:string){await pool.query("INSERT INTO raw_attendance_punches(biometric_id,punch_time,source_event_key) VALUES($1,$2,$3)",[bio,`${day}T${time}+05:30`,`${marker}-${key}`]);}
describe("attendance status evaluator",()=>{beforeAll(async()=>{shift=(await pool.query("INSERT INTO shifts(name,start_time,end_time,grace_minutes,checkin_before_minutes,active) VALUES($1,'09:00','18:00',10,10,true) RETURNING id",[marker])).rows[0].id;employee=(await pool.query("INSERT INTO employees(biometric_id,name,joining_date,active) VALUES($1,$2,$3,true) RETURNING id",[bio,marker,day])).rows[0].id;await pool.query("INSERT INTO employee_shift_assignments(employee_id,shift_id,effective_from) VALUES($1,$2,$3)",[employee,shift,day]);});afterAll(async()=>{stopAttendanceStatusScheduler();await clear();await pool.query("DELETE FROM employee_shift_assignments WHERE employee_id=$1",[employee]);await pool.query("DELETE FROM employees WHERE id=$1",[employee]);await pool.query("DELETE FROM shifts WHERE id=$1",[shift]);});
it("is disabled in tests and starts only once",()=>{startAttendanceStatusScheduler();startAttendanceStatusScheduler();expect(attendanceSchedulerStarted()).toBe(false);});
it("evaluates pending and check-in-missing at fixed IST instants",async()=>{await clear();await evaluate("08:30:00");expect(await status()).toMatchObject({status:"PENDING"});await evaluate("09:20:00");expect(await status()).toMatchObject({status:"CHECK_IN_MISSING",note:"Check-in fingerprint missing"});});
it("evaluates currently-checked-in then missing-punch without fake times",async()=>{await clear();await punch("09:25:00","late");await evaluate("10:00:00");expect(await status()).toMatchObject({status:"CURRENTLY_CHECKED_IN",punch_out_at:null});await evaluate("18:16:00");expect(await status()).toMatchObject({status:"MISSING_PUNCH",punch_out_at:null});});
it("finalizes absent and present deterministically",async()=>{await clear();await evaluate("18:16:00");expect(await status()).toMatchObject({status:"ABSENT",punch_in_at:null,punch_out_at:null});await clear();await punch("09:00:00","in");await punch("18:00:00","out");await evaluate("18:16:00");expect(await status()).toMatchObject({status:"PRESENT",working_minutes:540});});
it("uses an advisory lock and repeated runs are idempotent",async()=>{await clear();const client=await pool.connect();try{await client.query("SELECT pg_advisory_lock($1)",[19019018]);expect(await evaluate("18:16:00")).toMatchObject({skipped:true});}finally{await client.query("SELECT pg_advisory_unlock($1)",[19019018]);client.release();}const first=await evaluate("18:16:00");const second=await evaluate("18:16:00");expect(first.skipped).toBe(false);expect(second.skipped).toBe(false);});
it("keeps check-in missing through the grace window",async()=>{await clear();await evaluate("09:05:00");expect(await status()).toMatchObject({status:"CHECK_IN_MISSING",note:"Awaiting check-in"});});
it("keeps one punch checked in during the checkout buffer",async()=>{await clear();await punch("09:00:00","buffer");await evaluate("18:10:00");expect(await status()).toMatchObject({status:"CURRENTLY_CHECKED_IN"});});
it("accepts an early punch inside the configured window",async()=>{await clear();await punch("08:55:00","early-ok");await evaluate("10:00:00");expect(await status()).toMatchObject({status:"CURRENTLY_CHECKED_IN",late_minutes:0});});
it("preserves excessively early punches outside the attendance window",async()=>{await clear();await punch("08:00:00","early-skip");await evaluate("10:00:00");expect(await status()).toMatchObject({status:"CHECK_IN_MISSING"});expect((await pool.query("SELECT count(*)::int count FROM raw_attendance_punches WHERE source_event_key=$1",[`${marker}-early-skip`])).rows[0].count).toBe(1);});
it("does not synthesize a checkout for one punch",async()=>{await clear();await punch("09:00:00","no-fake");await evaluate("18:16:00");expect((await status()).punch_out_at).toBeNull();});
it("does not double count an employee record",async()=>{await clear();await punch("09:00:00","count-in");await punch("18:00:00","count-out");await evaluate("18:16:00");expect((await pool.query("SELECT count(*)::int count FROM daily_attendance_records WHERE employee_id=$1 AND attendance_date=$2",[employee,day])).rows[0].count).toBe(1);});
it("is stable on repeated unchanged evaluation",async()=>{await clear();await evaluate("09:20:00");const first=await status();await evaluate("09:20:00");expect(await status()).toMatchObject({status:first.status,note:first.note});});
it("uses IST day boundaries from a UTC fixed instant",async()=>{await clear();process.env.ATTENDANCE_TEST_NOW="2993-07-10T03:30:00.000Z";await evaluateCurrentAttendanceStatuses(new Date(process.env.ATTENDANCE_TEST_NOW));expect(await status()).toMatchObject({status:"CHECK_IN_MISSING"});});
it("finalizes the previous IST date when evaluating the following day",async()=>{await clear();await punch("09:00:00","previous");process.env.ATTENDANCE_TEST_NOW="2993-07-11T00:00:00.000Z";await evaluateCurrentAttendanceStatuses(new Date(process.env.ATTENDANCE_TEST_NOW));expect(await status()).toMatchObject({status:"MISSING_PUNCH"});});
it("does not create raw punches during scheduler runs",async()=>{await clear();const before=(await pool.query("SELECT count(*)::int count FROM raw_attendance_punches WHERE biometric_id=$1",[bio])).rows[0].count;await evaluate("18:16:00");expect((await pool.query("SELECT count(*)::int count FROM raw_attendance_punches WHERE biometric_id=$1",[bio])).rows[0].count).toBe(before);});
it("keeps dashboard summary categories mutually exclusive",async()=>{await clear();await punch("09:00:00","summary");await evaluate("10:00:00");const row=await status();expect(["CURRENTLY_CHECKED_IN","MISSING_PUNCH","PRESENT","ABSENT","CHECK_IN_MISSING","PENDING"]).toContain(row.status);});
it("uses late status notes only when a late punch is recorded",async()=>{await clear();await punch("09:25:00","late-note");await evaluate("10:00:00");expect((await status()).note).toContain("Late by");});
it("does not overwrite a present record when no later inputs arrive",async()=>{await clear();await punch("09:00:00","present-in");await punch("18:00:00","present-out");await evaluate("18:16:00");await evaluate("19:00:00");expect(await status()).toMatchObject({status:"PRESENT",working_minutes:540});});
it("isolates a scheduler evaluation from unrelated employee data",async()=>{await clear();await evaluate("18:16:00");expect((await pool.query("SELECT count(*)::int count FROM daily_attendance_records WHERE employee_id=$1",[employee])).rows[0].count).toBe(1);});
it("reports a completed scheduler run when no competing lock exists",async()=>{await clear();const result=await evaluate("18:16:00");expect(result).toMatchObject({skipped:false});});});
