"use client";
import { useEffect,useState } from "react";
import { ApiError,apiClient } from "@/lib/api-client";
import { formatDateTime } from "@/lib/format";

type Device={id:string;device_code:string;name:string|null;model:string|null;serial_number:string|null;firmware_version:string|null;active:boolean;status:"ONLINE"|"OFFLINE";last_seen:string|null;last_ip:string|null;last_raw_punch_received:string|null};
type Punch={id:string;biometric_id:string;punch_time:string;punch_state:string|null;verify_mode:string|null;received_at:string};
const empty={device_code:"",name:"",model:"MB160",serial_number:"",firmware_version:""};

export default function DevicesPage(){
 const [devices,setDevices]=useState<Device[]>([]),[selected,setSelected]=useState<Device|null>(null),[punches,setPunches]=useState<Punch[]>([]),[role,setRole]=useState("MANAGER"),[form,setForm]=useState(empty),[editing,setEditing]=useState(false),[error,setError]=useState("");
 const load=async()=>{try{const [list,user]=await Promise.all([apiClient.get("/devices"),apiClient.get("/auth/me")]);const rows=list as Device[];setDevices(rows);setRole(String(user.role));const next=selected?rows.find(d=>d.id===selected.id)??rows[0]:rows[0];setSelected(next??null);if(next)setPunches(await apiClient.get(`/devices/${next.id}/recent-punches`) as Punch[]);else setPunches([])}catch{setError("Failed to load biometric devices")}};
 useEffect(()=>{Promise.all([apiClient.get("/devices"),apiClient.get("/auth/me")]).then(async([list,user])=>{const rows=list as Device[];setDevices(rows);setRole(String(user.role));setSelected(rows[0]??null);if(rows[0])setPunches(await apiClient.get(`/devices/${rows[0].id}/recent-punches`) as Punch[])}).catch(()=>setError("Failed to load biometric devices"))},[]);
 const choose=async(d:Device)=>{setSelected(d);setPunches(await apiClient.get(`/devices/${d.id}/recent-punches`) as Punch[])};
 const save=async(e:React.FormEvent)=>{e.preventDefault();setError("");try{const payload=Object.fromEntries(Object.entries(form).map(([k,v])=>[k,v.trim()||null]));if(editing&&selected)await apiClient.patch(`/devices/${selected.id}`,payload);else await apiClient.post("/devices",payload);setEditing(false);setForm(empty);await load()}catch(e){setError(e instanceof ApiError?e.message:"Unable to save device")}};
 const edit=()=>{if(!selected)return;setEditing(true);setForm({device_code:selected.device_code,name:selected.name??"",model:selected.model??"",serial_number:selected.serial_number??"",firmware_version:selected.firmware_version??""})};
 const toggle=async()=>{if(!selected)return;await apiClient.patch(`/devices/${selected.id}/${selected.active?"deactivate":"activate"}`,{});await load()};
 return <div className="space-y-6"><div className="flex justify-between items-center"><div><h1 className="text-2xl font-semibold">Biometric Device</h1><p className="text-sm text-gray-500">Registered biometric machines and unprocessed device activity</p></div>{role==="ADMIN"&&<button onClick={()=>{setEditing(true);setSelected(null);setForm(empty)}} className="px-4 py-2 bg-[#028174] text-white rounded">Add Device</button>}</div>
 {error&&<div className="p-3 bg-red-100 text-[#DC2626] rounded">{error}</div>}
 {editing&&role==="ADMIN"&&<form onSubmit={save} className="bg-white p-5 rounded shadow grid grid-cols-1 md:grid-cols-2 gap-4">{Object.keys(empty).map(k=><label key={k} className="text-sm capitalize">{k.replaceAll("_"," ")}{k==="device_code"&&" *"}<input required={k==="device_code"} value={form[k as keyof typeof form]} onChange={e=>setForm({...form,[k]:e.target.value})} className="block mt-1 w-full border rounded px-3 py-2"/></label>)}<div className="md:col-span-2 flex justify-end gap-3"><button type="button" onClick={()=>setEditing(false)} className="px-4 py-2 border rounded">Cancel</button><button className="px-4 py-2 bg-[#028174] text-white rounded">Save Device</button></div></form>}
 <div className="grid grid-cols-1 lg:grid-cols-3 gap-6"><div className="bg-white rounded shadow divide-y">{devices.map(d=><button key={d.id} onClick={()=>void choose(d)} className={`w-full text-left p-4 ${selected?.id===d.id?"bg-emerald-50":""}`}><div className="font-semibold">{d.name||d.device_code}</div><div className="text-sm text-gray-500">{d.model||"Model not set"} · {d.device_code}</div></button>)}{!devices.length&&<div className="p-6 text-gray-500">No devices configured.</div>}</div>
 <div className="lg:col-span-2 space-y-6">{selected&&<div className="bg-white p-6 rounded shadow"><div className="flex justify-between"><div><h2 className="text-xl font-semibold">{selected.name||selected.device_code}</h2><span className={`inline-block mt-2 px-3 py-1 rounded-full text-sm font-semibold text-white ${selected.status==="ONLINE"?"bg-[#0AB68B]":"bg-[#DC2626]"}`}>{selected.status}</span></div>{role==="ADMIN"&&<div className="space-x-2"><button onClick={edit} className="px-3 py-2 border rounded">Edit</button><button onClick={()=>void toggle()} className={`px-3 py-2 text-white rounded ${selected.active?"bg-[#DC2626]":"bg-[#0AB68B]"}`}>{selected.active?"Deactivate":"Activate"}</button></div>}</div><dl className="grid grid-cols-2 gap-4 mt-5 text-sm">{[["Device code",selected.device_code],["Serial number",selected.serial_number||"—"],["Firmware",selected.firmware_version||"—"],["Last IP",selected.last_ip||"—"],["Last sync",formatDateTime(selected.last_seen)],["Last raw punch",formatDateTime(selected.last_raw_punch_received)],["Configuration",selected.active?"Active":"Inactive"]].map(([a,b])=><div key={a}><dt className="text-gray-500">{a}</dt><dd className="font-medium">{b}</dd></div>)}</dl></div>}
 <div className="bg-white rounded shadow overflow-hidden"><h2 className="p-5 text-lg font-semibold">Recent Raw Device Punches</h2><table className="w-full text-left text-sm"><thead className="bg-gray-50"><tr><th className="p-3">Biometric ID</th><th className="p-3">Punch time</th><th className="p-3">State</th><th className="p-3">Verify mode</th><th className="p-3">Received</th></tr></thead><tbody>{punches.map(p=><tr key={p.id} className="border-t"><td className="p-3 font-medium">{p.biometric_id}</td><td className="p-3">{formatDateTime(p.punch_time)}</td><td className="p-3">{p.punch_state??"—"}</td><td className="p-3">{p.verify_mode??"—"}</td><td className="p-3">{formatDateTime(p.received_at)}</td></tr>)}{!punches.length&&<tr><td colSpan={5} className="p-5 text-center text-gray-500">No raw punches received.</td></tr>}</tbody></table></div></div></div></div>
}
