/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/exhaustive-deps */
"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { ConfirmationModal } from "@/components/confirmation-modal";
import { usePayrollModule } from "@/components/payroll-module-context";
import { apiClient } from "@/lib/api-client";

const inr=(v:unknown)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(Number(v??0));
export default function PayrollDetail(){
 const {id}=useParams<{id:string}>();const {payrollEnabled}=usePayrollModule();const [period,setPeriod]=useState<any>();const [records,setRecords]=useState<any[]>([]);const [payments,setPayments]=useState<any[]>([]);const [user,setUser]=useState<any>();const [selectedRecords,setSelectedRecords]=useState<string[]>([]);const [selectedPayments,setSelectedPayments]=useState<string[]>([]);const [action,setAction]=useState<"records"|"payments"|null>(null);const [reason,setReason]=useState("");const [message,setMessage]=useState("");const [working,setWorking]=useState(false);
 const load=()=>Promise.all([apiClient.get(`/payroll/periods/${id}`),apiClient.get(`/payroll/periods/${id}/records`),apiClient.get(`/payroll/periods/${id}/payments`),apiClient.get("/auth/me")]).then(([p,r,pay,u])=>{setPeriod(p);setRecords(r as any[]);setPayments(pay as any[]);setUser(u);}).catch((e:Error)=>setMessage(e.message));
 useEffect(()=>{void load();},[id]);
 const canReset=payrollEnabled&&user?.role==="ADMIN";const toggle=(value:string,values:string[],setValues:(ids:string[])=>void)=>setValues(values.includes(value)?values.filter(id=>id!==value):[...values,value]);
 const reset=async()=>{if(!action||!reason.trim()){setMessage("A reset reason is required.");return;}setWorking(true);try{const ids=action==="records"?selectedRecords:selectedPayments;await apiClient.delete(action==="records"?"/payroll/records/bulk-reset":"/payroll/payments/bulk-reset",{body:JSON.stringify({ids,reason}),headers:{"Content-Type":"application/json"}});setAction(null);setReason("");setSelectedRecords([]);setSelectedPayments([]);setMessage("Selected payroll data was reset. Master and attendance data was preserved.");await load();}catch(e){setMessage(e instanceof Error?e.message:"Reset failed");}finally{setWorking(false);}};
 if(!period)return <div>{message||"Loading..."}</div>;
 return <div className="space-y-5"><Link className="text-blue-700" href="/payroll">← Payroll Periods</Link><h1 className="text-2xl font-bold">Payroll {period.month}/{period.year} — {period.status}</h1>{message&&<p className="rounded bg-blue-50 p-3" role="status">{message}</p>}
  <section className="rounded bg-white shadow"><div className="flex flex-wrap items-center gap-2 border-b p-3 text-sm"><span>{selectedRecords.length} employee records selected</span>{canReset&&<><button disabled={!selectedRecords.length||working} className="border px-2 py-1 text-red-700 disabled:opacity-50" onClick={()=>setAction("records")}>Clear Selected Payroll Records</button><button disabled={!selectedRecords.length||working} className="border px-2 py-1 disabled:opacity-50" onClick={()=>setSelectedRecords([])}>Clear Selection</button></>}</div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b">{canReset&&<th className="p-2"><input aria-label="Select all payroll employee records" type="checkbox" checked={records.length>0&&records.every(r=>selectedRecords.includes(r.id))} onChange={()=>setSelectedRecords(records.every(r=>selectedRecords.includes(r.id))?[]:records.map(r=>r.id))}/></th>}{["Employee","Salary","Gross","Net","Status"].map(x=><th className="p-2 text-left" key={x}>{x}</th>)}</tr></thead><tbody>{records.map(r=><tr className="border-b" key={r.id}>{canReset&&<td className="p-2"><input aria-label={`Select payroll record ${r.employee_name}`} type="checkbox" checked={selectedRecords.includes(r.id)} onChange={()=>toggle(r.id,selectedRecords,setSelectedRecords)}/></td>}<td className="p-2"><Link className="text-blue-700" href={`/payroll/records/${r.id}`}>{r.employee_name}</Link></td><td className="p-2">{inr(r.base_salary)}</td><td className="p-2">{inr(r.gross_pay)}</td><td className="p-2">{inr(r.net_pay)}</td><td className="p-2">{r.status}</td></tr>)}</tbody></table></div></section>
  <section className="rounded bg-white shadow"><div className="flex flex-wrap items-center gap-2 border-b p-3 text-sm"><h2 className="mr-2 font-semibold">Payment history</h2><span>{selectedPayments.length} payment records selected</span>{canReset&&<><button disabled={!selectedPayments.length||working} className="border px-2 py-1 text-red-700 disabled:opacity-50" onClick={()=>setAction("payments")}>Clear Selected Payment Records</button><button disabled={!selectedPayments.length||working} className="border px-2 py-1 disabled:opacity-50" onClick={()=>setSelectedPayments([])}>Clear Selection</button></>}</div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b">{canReset&&<th className="p-2"><input aria-label="Select all payment records" type="checkbox" checked={payments.length>0&&payments.every(pay=>selectedPayments.includes(pay.id))} onChange={()=>setSelectedPayments(payments.every(pay=>selectedPayments.includes(pay.id))?[]:payments.map(pay=>pay.id))}/></th>}{["Employee","Amount","Method","Reference","Status"].map(x=><th className="p-2 text-left" key={x}>{x}</th>)}</tr></thead><tbody>{payments.map(pay=><tr className="border-b" key={pay.id}>{canReset&&<td className="p-2"><input aria-label={`Select payment ${pay.id}`} type="checkbox" checked={selectedPayments.includes(pay.id)} onChange={()=>toggle(pay.id,selectedPayments,setSelectedPayments)}/></td>}<td className="p-2">{pay.employee_name}</td><td className="p-2">{inr(pay.amount)}</td><td className="p-2">{pay.payment_method}</td><td className="p-2">{pay.payment_reference||"—"}</td><td className="p-2">{pay.status}</td></tr>)}</tbody></table></div></section>
  <ConfirmationModal open={action!==null} pending={working} recordName="payroll data" title={action==="payments"?"Clear selected payment records?":"Clear selected payroll employee records?"} message="This reset permanently removes linked payroll payments, salary slips, deductions, and employee payroll records. It may remove the payroll period when no dependent payroll records remain. Employee, salary, attendance, shifts, raw punches, and unrelated advance history are preserved. A reset reason is required and the action is audited." confirmLabel="Clear Selected" onCancel={()=>setAction(null)} onConfirm={()=>void reset()}><textarea aria-label="Reset reason" className="w-full border p-2" placeholder="Reset reason (required)" value={reason} onChange={e=>setReason(e.target.value)}/></ConfirmationModal>
 </div>;
}
