/* eslint-disable @typescript-eslint/no-explicit-any */
import { getDatabasePool } from "../../infrastructure/database/database.js";
import type { Pool, PoolClient } from "pg";
const pool=getDatabasePool();
const money=(n:number)=>Math.round((n+Number.EPSILON)*100)/100;
const n=(v:unknown)=>Number(v??0);
function immutable(period:{status:string}, record?:{status:string}) { if(["APPROVED","PAID","LOCKED","CANCELLED"].includes(period.status)||record?.status==="PAID"||record?.status==="CANCELLED") throw new Error("Validation: This payroll record is read-only"); }

export async function listPeriods(){return (await pool.query(`SELECT p.*,count(r.id)::int employee_count,coalesce(sum(r.gross_pay),0) gross_total,coalesce(sum(r.attendance_deduction+r.other_deductions),0) deduction_total,coalesce(sum(r.advance_recovery),0) advance_recovery_total,coalesce(sum(r.net_pay),0) net_pay_total,CASE WHEN p.status='CANCELLED' AND count(r.id)=0 AND NOT EXISTS(SELECT 1 FROM payroll_payments pp WHERE pp.payroll_period_id=p.id) AND NOT EXISTS(SELECT 1 FROM payroll_slips ps WHERE ps.payroll_period_id=p.id) THEN true ELSE false END AS can_delete_empty_cancelled,CASE WHEN p.status IN ('DRAFT','GENERATED','APPROVED','CANCELLED') AND NOT EXISTS(SELECT 1 FROM payroll_payments pp WHERE pp.payroll_period_id=p.id) AND NOT EXISTS(SELECT 1 FROM payroll_slips ps WHERE ps.payroll_period_id=p.id) AND NOT EXISTS(SELECT 1 FROM employee_advance_transactions at JOIN employee_payroll_records rr ON rr.id=at.payroll_record_id WHERE rr.payroll_period_id=p.id) THEN true ELSE false END AS can_clear_unpaid_test,CASE WHEN p.status='PAID' THEN 'PAID payrolls cannot be cleared' WHEN p.status='LOCKED' THEN 'LOCKED payrolls cannot be cleared' WHEN EXISTS(SELECT 1 FROM payroll_payments pp WHERE pp.payroll_period_id=p.id) THEN 'Payment-linked payrolls cannot be cleared' WHEN EXISTS(SELECT 1 FROM payroll_slips ps WHERE ps.payroll_period_id=p.id) THEN 'Salary-slip-linked payrolls cannot be cleared' WHEN EXISTS(SELECT 1 FROM employee_advance_transactions at JOIN employee_payroll_records rr ON rr.id=at.payroll_record_id WHERE rr.payroll_period_id=p.id) THEN 'Advance-repayment-linked payrolls cannot be cleared' ELSE NULL END AS clear_block_reason FROM payroll_periods p LEFT JOIN employee_payroll_records r ON r.payroll_period_id=p.id GROUP BY p.id ORDER BY year DESC,month DESC,p.created_at DESC`)).rows;}
const periodColumns="id,year,month,period_start::text AS period_start,period_end::text AS period_end,status,generated_at,generated_by,approved_at,approved_by,approval_notes,paid_at,paid_by,payment_reference,payment_notes,locked_at,locked_by,notes,cancellation_reason,created_at,updated_at";
export async function getPeriod(id:string){const r=await pool.query(`SELECT ${periodColumns} FROM payroll_periods WHERE id=$1`,[id]);if(!r.rows[0])throw new Error("Not Found: Payroll period not found");return r.rows[0];}
export async function createPeriod(input:{year?:number;month?:number;notes?:string}, userId:string){const year=Number(input.year),month=Number(input.month);if(!Number.isInteger(year)||!Number.isInteger(month)||month<1||month>12)throw new Error("Validation: A valid year and month are required");const active=await pool.query("SELECT 1 FROM payroll_periods WHERE year=$1 AND month=$2 AND status <> 'CANCELLED' LIMIT 1",[year,month]);if(active.rowCount)throw new Error("Conflict: A payroll period already exists for this month");const start=`${year}-${String(month).padStart(2,"0")}-01`;const end=new Date(Date.UTC(year,month,0)).toISOString().slice(0,10);try{return (await pool.query(`INSERT INTO payroll_periods(year,month,period_start,period_end,notes,generated_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING ${periodColumns}`,[year,month,start,end,input.notes??null,userId])).rows[0];}catch(e){if((e as {code?:string}).code==="23505")throw new Error("Conflict: A payroll period already exists for this month");throw e;}}

export async function createReplacement(id:string,userId:string){
 const c=await pool.connect();try{await c.query("BEGIN");const source=(await c.query(`SELECT ${periodColumns} FROM payroll_periods WHERE id=$1 FOR UPDATE`,[id])).rows[0];if(!source)throw new Error("Not Found: Payroll period not found");if(source.status!=="CANCELLED")throw new Error("Conflict: Only CANCELLED payroll periods can be replaced");await c.query("SELECT pg_advisory_xact_lock(hashtext($1))",[`payroll-replacement-${source.year}-${source.month}`]);const existing=(await c.query(`SELECT ${periodColumns} FROM payroll_periods WHERE year=$1 AND month=$2 AND status<>'CANCELLED' FOR UPDATE`,[source.year,source.month])).rows[0];if(existing){await c.query("COMMIT");return {period:existing,created:false,message:"A replacement payroll period already exists for this month"};}const created=(await c.query(`INSERT INTO payroll_periods(year,month,period_start,period_end,status,notes,generated_by) VALUES($1,$2,$3,$4,'DRAFT',$5,$6) RETURNING ${periodColumns}`,[source.year,source.month,source.period_start,source.period_end,`Replacement for cancelled payroll ${source.id}`,userId])).rows[0];await c.query("COMMIT");return {period:created,created:true,message:"Replacement DRAFT payroll period created"};}catch(e){await c.query("ROLLBACK");if((e as {code?:string}).code==="23505")throw new Error("Conflict: A replacement payroll period already exists for this month");throw e;}finally{c.release();}
}

async function period(id:string){return getPeriod(id) as Promise<{id:string;period_start:string;period_end:string;status:string}>;}
async function deductions(recordId:string){return (await pool.query("SELECT * FROM payroll_deductions WHERE payroll_record_id=$1 ORDER BY created_at",[recordId])).rows;}
async function recalcRecord(p:{id:string;period_start:string;period_end:string;status:string}, employee:{id:string;joining_date:string|null}, salary:any, existing:any){
 const attendance=(await pool.query(`SELECT status,count(*)::int count,coalesce(sum(working_minutes),0)::int work FROM daily_attendance_records WHERE employee_id=$1 AND attendance_date BETWEEN $2 AND $3 GROUP BY status`,[employee.id,p.period_start,p.period_end])).rows;
 const counts:Record<string,number>={};let work=0; for(const a of attendance){counts[a.status]=n(a.count??1);work+=n(a.work);}
 // Query rows rather than raw punches; missing calendar dates are treated as absence only within employment/salary eligibility.
 const joined=employee.joining_date&&employee.joining_date>p.period_start?employee.joining_date:p.period_start;
 const calendar=Math.floor((Date.parse(`${p.period_end}T00:00:00Z`)-Date.parse(`${joined}T00:00:00Z`))/86400000)+1;
 const present=(counts.PRESENT??0),late=(counts.LATE??0),early=(counts.EARLY_EXIT??0),lateEarly=(counts.LATE_AND_EARLY_EXIT??0),half=(counts.HALF_DAY??0),weekly=(counts.WEEKLY_OFF??0),holiday=(counts.HOLIDAY??0),missing=(counts.MISSING_PUNCH??0),noShift=(counts.NO_SHIFT??0),unmatched=(counts.UNMATCHED??0);
 const recorded=present+late+early+lateEarly+half+weekly+holiday+missing+noShift+unmatched+(counts.ABSENT??0); const absent=Math.max(counts.ABSENT??0,Math.max(0,calendar-recorded)); const payable=present+late+early+lateEarly+half*.5+weekly+holiday;
 const base=n(salary.monthly_salary??salary.daily_rate??salary.hourly_rate); let attendanceDeduction=0,gross=0;
 if(salary.salary_type==="MONTHLY"){const daily=base/(new Date(Date.UTC(Number(p.period_start.slice(0,4)),Number(p.period_start.slice(5,7)),0)).getUTCDate());attendanceDeduction=money(daily*Math.max(0,calendar-payable));gross=money(base);}
 if(salary.salary_type==="DAILY")gross=money(payable*base);
 if(salary.salary_type==="HOURLY")gross=money((work/60)*base);
 const ds=existing?await deductions(existing.id):[]; const other=money(ds.reduce((s,d)=>s+n(d.amount),0)); const recovery=n(existing?.advance_recovery); const net=money(Math.max(0,gross-attendanceDeduction-other-recovery)); const details={method:"calendar-day proration",calendar_days:new Date(Date.UTC(Number(p.period_start.slice(0,4)),Number(p.period_start.slice(5,7)),0)).getUTCDate(),eligible_employment_days:calendar,payable_day_equivalent:payable,total_work_minutes:work,early_exit_days:early,late_and_early_exit_days:lateEarly,no_shift_days:noShift,unmatched_days:unmatched,unpaid_balance:money(Math.max(0,attendanceDeduction+other+recovery-gross))};
 const vals=[p.id,employee.id,salary.id,salary.salary_type,money(base),payable,present,late,half,absent,weekly,holiday,missing,work,attendanceDeduction,other,recovery,gross,net,JSON.stringify(details)];
 if(existing) return (await pool.query(`UPDATE employee_payroll_records SET salary_history_id=$1,salary_type=$2,base_salary=$3,payable_days=$4,present_days=$5,late_days=$6,half_days=$7,absent_days=$8,weekly_off_days=$9,holiday_days=$10,missing_punch_days=$11,total_work_minutes=$12,attendance_deduction=$13,other_deductions=$14,advance_recovery=$15,gross_pay=$16,net_pay=$17,calculation_details=$18 WHERE id=$19 RETURNING *`,[...vals.slice(2),existing.id])).rows[0];
 return (await pool.query(`INSERT INTO employee_payroll_records(payroll_period_id,employee_id,salary_history_id,salary_type,base_salary,payable_days,present_days,late_days,half_days,absent_days,weekly_off_days,holiday_days,missing_punch_days,total_work_minutes,attendance_deduction,other_deductions,advance_recovery,gross_pay,net_pay,calculation_details) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20) RETURNING *`,vals)).rows[0];
}
export async function generate(id:string,userId:string,recalculateExisting=false){const p=await period(id);if(["APPROVED","PAID","LOCKED","CANCELLED"].includes(p.status))throw new Error("Validation: This payroll period cannot be generated");const employees=(await pool.query("SELECT id,joining_date::text,active FROM employees WHERE joining_date IS NULL OR joining_date <= $1",[p.period_end])).rows;let created=0,updated=0,eligibleEmployeeCount=0;const skippedEmployees:{employee_id:string;reason:string}[]=[];for(const e of employees){if(!e.active){skippedEmployees.push({employee_id:e.id,reason:"INACTIVE_EMPLOYEE"});continue;}const salary=(await pool.query("SELECT * FROM employee_salary_history WHERE employee_id=$1 AND active AND effective_from <= $3::date AND (effective_to IS NULL OR effective_to >= $2::date) ORDER BY effective_from DESC LIMIT 1",[e.id,p.period_start,p.period_end])).rows[0];if(!salary){skippedEmployees.push({employee_id:e.id,reason:"NO_ACTIVE_SALARY"});continue;}const amount=n(salary.salary_type==="MONTHLY"?salary.monthly_salary:salary.salary_type==="DAILY"?salary.daily_rate:salary.hourly_rate);if(!Number.isFinite(amount)||amount<=0){skippedEmployees.push({employee_id:e.id,reason:"INVALID_SALARY"});continue;}eligibleEmployeeCount++;const existing=(await pool.query("SELECT * FROM employee_payroll_records WHERE payroll_period_id=$1 AND employee_id=$2",[id,e.id])).rows[0];if(existing){if(recalculateExisting&&existing.status!=="PAID"&&existing.status!=="CANCELLED"){await recalcRecord(p,e,salary,existing);updated++;}else skippedEmployees.push({employee_id:e.id,reason:"ALREADY_GENERATED"});continue;}await recalcRecord(p,e,salary,undefined);created++;}await pool.query("UPDATE payroll_periods SET status='GENERATED',generated_at=coalesce(generated_at,now()),generated_by=$2 WHERE id=$1",[id,userId]);return {eligibleEmployeeCount,generatedCount:created,updatedCount:updated,skippedCount:skippedEmployees.length,skippedEmployees,created,updated,skipped_employee_ids:skippedEmployees.map((employee)=>employee.employee_id)};}
export async function recalculate(id:string,userId:string){const p=await period(id);if(p.status==="LOCKED"||p.status==="CANCELLED")throw new Error("Validation: This payroll period cannot be recalculated");return generate(id,userId,true);}
export async function listRecords(id:string){await period(id);return (await pool.query(`SELECT r.*,e.name employee_name,e.biometric_id FROM employee_payroll_records r JOIN employees e ON e.id=r.employee_id WHERE r.payroll_period_id=$1 ORDER BY e.name`,[id])).rows;}
export async function getRecord(id:string){const r=await pool.query(`SELECT r.*,p.status period_status,p.period_end::text,e.name employee_name,e.biometric_id,s.effective_from::text salary_effective_from,s.effective_to::text salary_effective_to FROM employee_payroll_records r JOIN payroll_periods p ON p.id=r.payroll_period_id JOIN employees e ON e.id=r.employee_id JOIN employee_salary_history s ON s.id=r.salary_history_id WHERE r.id=$1`,[id]);if(!r.rows[0])throw new Error("Not Found: Payroll record not found");return {...r.rows[0],deductions:await deductions(id)};}
export async function updateRecord(id:string,input:{advance_recovery?:number}){const r:any=await getRecord(id);immutable({status:r.period_status},r);if(input.advance_recovery===undefined)throw new Error("Validation: advance_recovery is required");const recovery=money(Number(input.advance_recovery));if(!Number.isFinite(recovery)||recovery<0)throw new Error("Validation: Advance recovery must be non-negative");const balance=n((await pool.query(`SELECT coalesce(sum(CASE WHEN transaction_type IN ('OPENING_ADVANCE','ADVANCE_GIVEN','ADJUSTMENT') THEN amount ELSE -amount END),0) balance FROM employee_advance_transactions WHERE employee_id=$1`,[r.employee_id])).rows[0].balance);if(recovery>balance)throw new Error("Validation: Advance recovery cannot exceed the pending advance balance");if(recovery>n(r.gross_pay)-n(r.other_deductions))throw new Error("Validation: Advance recovery cannot make net pay negative");return (await pool.query("UPDATE employee_payroll_records SET advance_recovery=$2,net_pay=$3 WHERE id=$1 RETURNING *",[id,recovery,money(n(r.gross_pay)-n(r.other_deductions)-recovery)])).rows[0];}
export async function updateRecordStatus(id:string,status:string,userId:string,role:string){const r:any=await getRecord(id);immutable({status:r.period_status},r);if(!["DRAFT","APPROVED","PAID","CANCELLED"].includes(status))throw new Error("Validation: Invalid payroll record status");if(status==="PAID"&&role!=="ADMIN")throw new Error("Validation: Only ADMIN can mark payroll records PAID");if(status==="PAID")await repay(r,userId);return (await pool.query("UPDATE employee_payroll_records SET status=$2 WHERE id=$1 RETURNING *",[id,status])).rows[0];}
async function assertEditable(id:string){const r:any=await getRecord(id);immutable({status:r.period_status},r);return r;}
async function refreshTotals(id:string){const r:any=await getRecord(id);const other=money((await deductions(id)).reduce((s,d)=>s+n(d.amount),0));await pool.query("UPDATE employee_payroll_records SET other_deductions=$2,net_pay=$3 WHERE id=$1",[id,other,money(Math.max(0,n(r.gross_pay)-other-n(r.advance_recovery)))]);}
export async function addDeduction(id:string,input:any){await assertEditable(id);const amount=money(Number(input.amount));if(!["OTHER","DAMAGE","LOAN","PENALTY"].includes(input.deduction_type)||amount<=0)throw new Error("Validation: Valid positive deduction is required");const d=(await pool.query("INSERT INTO payroll_deductions(payroll_record_id,deduction_type,amount,notes) VALUES($1,$2,$3,$4) RETURNING *",[id,input.deduction_type,amount,input.notes??null])).rows[0];await refreshTotals(id);return d;}
export async function updateDeduction(id:string,did:string,input:any){await assertEditable(id);const amount=input.amount===undefined?undefined:money(Number(input.amount));if(amount!==undefined&&amount<=0)throw new Error("Validation: Deduction amount must be positive");const d=(await pool.query("UPDATE payroll_deductions SET deduction_type=coalesce($3,deduction_type),amount=coalesce($4,amount),notes=CASE WHEN $5 THEN $6 ELSE notes END WHERE id=$2 AND payroll_record_id=$1 RETURNING *",[id,did,input.deduction_type??null,amount??null,input.notes!==undefined,input.notes??null])).rows[0];if(!d)throw new Error("Not Found: Deduction not found");await refreshTotals(id);return d;}
export async function deleteDeduction(id:string,did:string){await assertEditable(id);const d=await pool.query("DELETE FROM payroll_deductions WHERE id=$2 AND payroll_record_id=$1 RETURNING id",[id,did]);if(!d.rows[0])throw new Error("Not Found: Deduction not found");await refreshTotals(id);}
async function repay(r:any,userId:string){if(n(r.advance_recovery)<=0)return;await pool.query("INSERT INTO employee_advance_transactions(employee_id,transaction_type,amount,transaction_date,notes,created_by,payroll_record_id) VALUES($1,'REPAYMENT',$2,$3,$4,$5,$6) ON CONFLICT (payroll_record_id) WHERE payroll_record_id IS NOT NULL DO NOTHING",[r.employee_id,r.advance_recovery,r.period_end,`Payroll recovery for period ${r.payroll_period_id}`,userId,r.id]);}
export async function lock(id:string,userId:string){const p:any=await period(id);if(p.status==="LOCKED")return p;if(p.status==="CANCELLED")throw new Error("Validation: Cancelled payroll cannot be locked");const records=await listRecords(id);for(const r of records){if(r.status!=="CANCELLED")await repay({...r,period_end:p.period_end},userId);}return (await pool.query("UPDATE payroll_periods SET status='LOCKED',locked_at=now(),locked_by=$2 WHERE id=$1 RETURNING *",[id,userId])).rows[0];}
export async function cancel(id:string,cancellationReason?:string){const p:any=await period(id);if(p.status==="LOCKED")throw new Error("Validation: A locked payroll period cannot be cancelled");if(p.status==="CANCELLED")return p;return (await pool.query("UPDATE payroll_periods SET status='CANCELLED',cancellation_reason=$2 WHERE id=$1 RETURNING *",[id,cancellationReason?.trim()||null])).rows[0];}
export async function approve(id:string,notes:string|undefined,userId:string){
 const c=await pool.connect();try{await c.query("BEGIN");const p=(await c.query(`SELECT ${periodColumns} FROM payroll_periods WHERE id=$1 FOR UPDATE`,[id])).rows[0];if(!p)throw new Error("Not Found: Payroll period not found");if(p.status==="APPROVED"||p.status==="PAID"){await c.query("COMMIT");return p;}if(p.status!=="GENERATED")throw new Error("Conflict: Only GENERATED payroll can be approved");const records=(await c.query("SELECT * FROM employee_payroll_records WHERE payroll_period_id=$1 FOR UPDATE",[id])).rows;if(!records.length)throw new Error("Validation: Payroll must contain at least one employee record");if(records.some(r=>r.status==="CANCELLED"||n(r.net_pay)<0||r.calculation_details?.error))throw new Error("Validation: Payroll contains invalid employee records or calculation errors");await c.query("UPDATE employee_payroll_records SET status='APPROVED' WHERE payroll_period_id=$1 AND status='DRAFT'",[id]);const result=(await c.query(`UPDATE payroll_periods SET status='APPROVED',approved_at=coalesce(approved_at,now()),approved_by=coalesce(approved_by,$2),approval_notes=coalesce(approval_notes,$3) WHERE id=$1 RETURNING ${periodColumns}`,[id,userId,notes?.trim()||null])).rows[0];await c.query("COMMIT");return result;}catch(e){await c.query("ROLLBACK");throw e;}finally{c.release();}
}
const paymentMethods=["CASH","BANK_TRANSFER","UPI","CHEQUE","OTHER"];
export async function pay(id:string,input:{paymentMethod?:string;paymentReference?:string;paymentDate?:string;notes?:string},userId:string){
 if(!paymentMethods.includes(input.paymentMethod??""))throw new Error("Validation: A valid paymentMethod is required");if(!/^\d{4}-\d{2}-\d{2}$/.test(input.paymentDate??""))throw new Error("Validation: paymentDate must be YYYY-MM-DD");
 const c=await pool.connect();try{await c.query("BEGIN");const p=(await c.query(`SELECT ${periodColumns} FROM payroll_periods WHERE id=$1 FOR UPDATE`,[id])).rows[0];if(!p)throw new Error("Not Found: Payroll period not found");if(p.status==="PAID"){await c.query("COMMIT");return p;}if(p.status!=="APPROVED")throw new Error("Conflict: Only APPROVED payroll can be paid");const records=(await c.query("SELECT * FROM employee_payroll_records WHERE payroll_period_id=$1 FOR UPDATE",[id])).rows;if(!records.length||records.some(r=>r.status!=="APPROVED"))throw new Error("Validation: Payroll records must all be approved before payment");for(const r of records){await c.query("INSERT INTO payroll_payments(payroll_period_id,payroll_record_id,employee_id,amount,payment_method,payment_reference,payment_date,status,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,'PAID',$8,$9) ON CONFLICT (payroll_record_id) DO NOTHING",[id,r.id,r.employee_id,r.net_pay,input.paymentMethod,input.paymentReference?.trim()||null,input.paymentDate,input.notes?.trim()||null,userId]);await repay({...r,period_end:p.period_end},userId);}await c.query("UPDATE employee_payroll_records SET status='PAID' WHERE payroll_period_id=$1",[id]);const result=(await c.query(`UPDATE payroll_periods SET status='PAID',paid_at=now(),paid_by=$2,payment_reference=$3,payment_notes=$4 WHERE id=$1 RETURNING ${periodColumns}`,[id,userId,input.paymentReference?.trim()||null,input.notes?.trim()||null])).rows[0];await c.query("COMMIT");return result;}catch(e){await c.query("ROLLBACK");throw e;}finally{c.release();}
}
const paymentSelect=`SELECT pp.id,pp.amount,pp.payment_method,pp.payment_reference,pp.payment_date::text,pp.status,pp.notes,pp.created_at,pp.updated_at,e.id employee_id,e.name employee_name,e.biometric_id,u.id created_by,u.username created_by_username,u.email created_by_email,reversal.reason reversal_reason,reversal.created_at reversal_created_at FROM payroll_payments pp JOIN employees e ON e.id=pp.employee_id JOIN app_users u ON u.id=pp.created_by LEFT JOIN LATERAL (SELECT reason,created_at FROM payroll_payment_audit WHERE payroll_payment_id=pp.id AND action='REVERSED' ORDER BY created_at DESC LIMIT 1) reversal ON true`;
export async function listPeriodPayments(id:string){await period(id);return (await pool.query(`${paymentSelect} WHERE pp.payroll_period_id=$1 ORDER BY e.name,pp.created_at`,[id])).rows;}
export async function listRecordPayments(id:string){await getRecord(id);return (await pool.query(`${paymentSelect} WHERE pp.payroll_record_id=$1 ORDER BY pp.created_at`,[id])).rows;}
export async function reversePayment(id:string,reason:string|undefined,userId:string){if(!reason?.trim())throw new Error("Validation: A reversal reason is required");const c=await pool.connect();try{await c.query("BEGIN");const payment=(await c.query("SELECT id,status FROM payroll_payments WHERE id=$1 FOR UPDATE",[id])).rows[0];if(!payment)throw new Error("Not Found: Payroll payment not found");if(payment.status==="REVERSED")throw new Error("Conflict: Payment has already been reversed");await c.query("UPDATE payroll_payments SET status='REVERSED' WHERE id=$1",[id]);await c.query("INSERT INTO payroll_payment_audit(payroll_payment_id,action,reason,created_by) VALUES($1,'REVERSED',$2,$3)",[id,reason.trim(),userId]);await c.query("COMMIT");return {id,status:"REVERSED"};}catch(e){await c.query("ROLLBACK");throw e;}finally{c.release();}}

async function slip(recordId:string,userId:string, db:Pool|PoolClient=pool){const record:any=(await db.query(`SELECT r.*,p.year,p.month,p.status period_status,p.approved_at,p.paid_at,approver.username approved_by_name,payer.username paid_by_name,e.name employee_name,e.biometric_id,e.designation,sh.name shift_name,pay.payment_method,pay.payment_reference,pay.status payment_status FROM employee_payroll_records r JOIN payroll_periods p ON p.id=r.payroll_period_id JOIN employees e ON e.id=r.employee_id LEFT JOIN app_users approver ON approver.id=p.approved_by LEFT JOIN app_users payer ON payer.id=p.paid_by LEFT JOIN LATERAL (SELECT s.name FROM employee_shift_assignments a JOIN shifts s ON s.id=a.shift_id WHERE a.employee_id=e.id AND a.effective_from<=p.period_end AND (a.effective_to IS NULL OR a.effective_to>=p.period_start) ORDER BY a.effective_from DESC LIMIT 1) sh ON true LEFT JOIN payroll_payments pay ON pay.payroll_record_id=r.id AND pay.status='PAID' WHERE r.id=$1`,[recordId])).rows[0];if(!record)throw new Error("Not Found: Payroll record not found");if(!["APPROVED","PAID"].includes(record.period_status))throw new Error("Conflict: Salary slips are available only for APPROVED or PAID payroll");const inserted=(await db.query("INSERT INTO payroll_slips(payroll_period_id,employee_payroll_record_id,employee_id,slip_number,generated_by) VALUES($1,$2,$3,$4,$5) ON CONFLICT (employee_payroll_record_id) DO NOTHING RETURNING *",[record.payroll_period_id,record.id,record.employee_id,`SAL-${record.year}${String(record.month).padStart(2,"0")}-${record.id.slice(0,8).toUpperCase()}`,userId])).rows[0];const meta=inserted??(await db.query("SELECT * FROM payroll_slips WHERE employee_payroll_record_id=$1",[recordId])).rows[0];return {...record,slip_number:meta.slip_number,slip_generated_at:meta.generated_at};}
export async function getSlip(recordId:string,userId:string){return slip(recordId,userId);}
export async function listSlips(periodId:string,userId:string){const p:any=await period(periodId);if(!["APPROVED","PAID"].includes(p.status))throw new Error("Conflict: Salary slips are available only for APPROVED or PAID payroll");const rows=(await pool.query("SELECT id FROM employee_payroll_records WHERE payroll_period_id=$1 ORDER BY created_at",[periodId])).rows;return Promise.all(rows.map(r=>slip(r.id,userId)));}
const escapeHtml=(value:unknown)=>String(value??"").replace(/[&<>"]/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"})[ch]!);
const formatMoney=(value:unknown)=>Number(value??0).toFixed(2);
export async function slipHtml(recordId:string,userId:string){const s:any=await slip(recordId,userId);const generated=new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Kolkata"}).format(new Date(s.slip_generated_at));const status=s.period_status==="PAID"?"PAID":"APPROVED — PAYMENT PENDING";return `<!doctype html><html><head><meta charset="utf-8"><title>Salary Slip ${escapeHtml(s.slip_number)}</title><style>body{font:14px Arial;color:#111;margin:32px}.head{display:flex;justify-content:space-between;border-bottom:2px solid #222}.grid{display:grid;grid-template-columns:1fr 1fr;gap:5px 24px;margin:20px 0}.amounts{width:100%;border-collapse:collapse}.amounts td{border:1px solid #aaa;padding:7px}.right{text-align:right}@media print{body{margin:16px}}</style></head><body><div class="head"><div><h1>Ranjirams Hotel</h1><p>Salary Slip · ${escapeHtml(s.year)}-${String(s.month).padStart(2,"0")} · ${escapeHtml(s.slip_number)}</p></div><h2>${status}</h2></div><div class="grid"><div><b>Employee:</b> ${escapeHtml(s.employee_name)}</div><div><b>Biometric ID:</b> ${escapeHtml(s.biometric_id)}</div><div><b>Designation:</b> ${escapeHtml(s.designation||"—")}</div><div><b>Shift:</b> ${escapeHtml(s.shift_name||"—")}</div><div><b>Salary type:</b> ${escapeHtml(s.salary_type)}</div><div><b>Generated (IST):</b> ${generated}</div><div><b>Approved by:</b> ${escapeHtml(s.approved_by_name||"—")}</div><div><b>Paid by:</b> ${escapeHtml(s.paid_by_name||"—")}</div></div><table class="amounts"><tr><td>Base salary</td><td class="right">${formatMoney(s.base_salary)}</td></tr><tr><td>Present / absent / late / paid leave / unpaid leave</td><td class="right">${s.present_days} / ${s.absent_days} / ${s.late_days} / ${s.weekly_off_days} / ${s.missing_punch_days}</td></tr><tr><td>Overtime (minutes)</td><td class="right">${s.total_work_minutes}</td></tr><tr><td>Gross salary</td><td class="right">${formatMoney(s.gross_pay)}</td></tr><tr><td>Attendance deduction</td><td class="right">${formatMoney(s.attendance_deduction)}</td></tr><tr><td>Salary deductions / manual deductions / advance deduction</td><td class="right">${formatMoney(s.other_deductions)} / ${formatMoney(s.other_deductions)} / ${formatMoney(s.advance_recovery)}</td></tr><tr><td>Additions / adjustments</td><td class="right">0.00</td></tr><tr><td><b>Net salary</b></td><td class="right"><b>${formatMoney(s.net_pay)}</b></td></tr></table><p><b>Payment:</b> ${escapeHtml(s.payment_status||status)} · ${escapeHtml(s.payment_method||"—")} · ${escapeHtml(s.payment_reference||"—")}</p></body></html>`;}
export async function slipPdf(recordId:string,userId:string){const s:any=await slip(recordId,userId);const lines=["HOTEL SALARY SLIP",`Slip: ${s.slip_number}    Period: ${s.year}-${String(s.month).padStart(2,"0")}`,`Employee: ${s.employee_name} (${s.biometric_id})`,`Designation: ${s.designation||"-"}    Shift: ${s.shift_name||"-"}`,`Base: ${formatMoney(s.base_salary)}  Gross: ${formatMoney(s.gross_pay)}  Net: ${formatMoney(s.net_pay)}`,`Attendance - Present: ${s.present_days}, Absent: ${s.absent_days}, Late: ${s.late_days}`,`Deductions: ${formatMoney(s.attendance_deduction+n(s.other_deductions))}  Advance: ${formatMoney(s.advance_recovery)}`,`Status: ${s.period_status==="PAID"?"PAID":"APPROVED - PAYMENT PENDING"}`,`Method: ${s.payment_method||"-"}  Reference: ${s.payment_reference||"-"}`,`Approved by: ${s.approved_by_name||"-"}  Paid by: ${s.paid_by_name||"-"}`].map(x=>x.replace(/[()\\\\]/g,"\\\\$&"));const stream=`BT /F1 11 Tf 50 760 Td 15 TL ${lines.map(x=>`(${x}) Tj T*`).join("\n")} ET`;const objects=["<< /Type /Catalog /Pages 2 0 R >>","<< /Type /Pages /Kids [3 0 R] /Count 1 >>","<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>","<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",`<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}\nendstream`];let pdf="%PDF-1.4\n";const offsets=[0];objects.forEach((o,i)=>{offsets.push(Buffer.byteLength(pdf));pdf+=`${i+1} 0 obj\n${o}\nendobj\n`;});const xref=Buffer.byteLength(pdf);pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(o=>String(o).padStart(10,"0")+" 00000 n ").join("\n")}\ntrailer << /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return Buffer.from(pdf,"utf8");}
export async function deleteDrafts(ids:string[]){if(!ids.length)throw new Error("Validation: Select at least one draft payroll period");const c=await pool.connect();try{await c.query("BEGIN");const invalid=await c.query("SELECT p.id FROM payroll_periods p WHERE p.id=ANY($1::uuid[]) AND (p.status<>'DRAFT' OR p.generated_at IS NOT NULL OR EXISTS(SELECT 1 FROM employee_payroll_records r WHERE r.payroll_period_id=p.id))",[ids]);if(invalid.rowCount)throw new Error("Conflict: Only unused DRAFT payroll periods can be deleted");const result=await c.query("DELETE FROM payroll_periods WHERE id=ANY($1::uuid[]) RETURNING id",[ids]);await c.query("COMMIT");return{deleted:result.rowCount??0};}catch(e){await c.query("ROLLBACK");throw e;}finally{c.release();}}

export async function deleteEmptyCancelled(ids:string[]){
 if(!ids.length)throw new Error("Validation: Select at least one empty cancelled payroll period");const c=await pool.connect();try{await c.query("BEGIN");const locked=(await c.query("SELECT id FROM payroll_periods WHERE id=ANY($1::uuid[]) FOR UPDATE",[ids])).rows;const found=new Set(locked.map((row:any)=>row.id));const rows=(await c.query(`SELECT p.id,p.status,COUNT(r.id)::int record_count,COALESCE(SUM(r.gross_pay),0) gross_total,COALESCE(SUM(r.attendance_deduction+r.other_deductions),0) deduction_total,COALESCE(SUM(r.advance_recovery),0) recovery_total,COALESCE(SUM(r.net_pay),0) net_total,EXISTS(SELECT 1 FROM payroll_payments pp WHERE pp.payroll_period_id=p.id) payment_exists,EXISTS(SELECT 1 FROM payroll_slips ps WHERE ps.payroll_period_id=p.id) slip_exists,EXISTS(SELECT 1 FROM payroll_payment_audit pa JOIN payroll_payments pp ON pp.id=pa.payroll_payment_id WHERE pp.payroll_period_id=p.id) audit_exists,EXISTS(SELECT 1 FROM employee_advance_transactions at JOIN employee_payroll_records rr ON rr.id=at.payroll_record_id WHERE rr.payroll_period_id=p.id) repayment_exists FROM payroll_periods p LEFT JOIN employee_payroll_records r ON r.payroll_period_id=p.id WHERE p.id=ANY($1::uuid[]) GROUP BY p.id`,[ids])).rows;const deleted:string[]=[];const blocked:{id:string;reason:string}[]=[];for(const row of rows){const empty=row.status==="CANCELLED"&&n(row.record_count)===0&&n(row.gross_total)===0&&n(row.deduction_total)===0&&n(row.recovery_total)===0&&n(row.net_total)===0&&!row.payment_exists&&!row.slip_exists&&!row.audit_exists&&!row.repayment_exists;if(!empty){blocked.push({id:row.id,reason:"Only empty CANCELLED payroll periods without payroll history can be deleted"});continue;}await c.query("DELETE FROM payroll_periods WHERE id=$1",[row.id]);deleted.push(row.id);}const skipped=ids.filter(id=>!found.has(id));await c.query("COMMIT");return{deleted:deleted.length,deleted_ids:deleted,skipped,blocked};}catch(e){await c.query("ROLLBACK");throw e;}finally{c.release();}
}

export async function clearUnpaidTestPeriods(ids:string[]){
 if(!ids.length)throw new Error("Validation: Select at least one unpaid test payroll period");
 const c=await pool.connect();
 try{
  await c.query("BEGIN");
  const locked=(await c.query("SELECT id FROM payroll_periods WHERE id=ANY($1::uuid[]) FOR UPDATE",[ids])).rows;
  const found=new Set(locked.map((row:any)=>row.id));
  const rows=(await c.query(`SELECT p.id,p.status,EXISTS(SELECT 1 FROM payroll_payments pp WHERE pp.payroll_period_id=p.id) payment_exists,EXISTS(SELECT 1 FROM payroll_slips ps WHERE ps.payroll_period_id=p.id) slip_exists,EXISTS(SELECT 1 FROM employee_advance_transactions at JOIN employee_payroll_records rr ON rr.id=at.payroll_record_id WHERE rr.payroll_period_id=p.id) repayment_exists FROM payroll_periods p WHERE p.id=ANY($1::uuid[])`,[ids])).rows;
  const cleared:string[]=[];
  const blocked:{id:string;reason:string}[]=[];
  for(const row of rows){
   const reason=row.status==='PAID'?'PAID payrolls cannot be cleared':row.status==='LOCKED'?'LOCKED payrolls cannot be cleared':!['DRAFT','GENERATED','APPROVED','CANCELLED'].includes(row.status)?'Payroll status cannot be cleared':row.payment_exists?'Payment-linked payrolls cannot be cleared':row.slip_exists?'Salary-slip-linked payrolls cannot be cleared':row.repayment_exists?'Advance-repayment-linked payrolls cannot be cleared':null;
   if(reason){blocked.push({id:row.id,reason});continue;}
   await c.query("DELETE FROM payroll_deductions WHERE payroll_record_id IN (SELECT id FROM employee_payroll_records WHERE payroll_period_id=$1)",[row.id]);
   await c.query("DELETE FROM employee_payroll_records WHERE payroll_period_id=$1",[row.id]);
   await c.query("DELETE FROM payroll_periods WHERE id=$1",[row.id]);
   cleared.push(row.id);
  }
  await c.query("COMMIT");
  return {cleared:cleared.length,cleared_ids:cleared,blocked,skipped:ids.filter(id=>!found.has(id))};
 }catch(e){await c.query("ROLLBACK");throw e;}finally{c.release();}
}

type ResetSummary={cleared:number;cleared_ids:string[];skipped:string[];blocked:{id:string;reason:string}[]};
async function resetAudit(c:PoolClient,input:{periodId?:string|null;recordId?:string|null;paymentId?:string|null;action:string;reason:string;actorId:string;metadata?:unknown}){await c.query("INSERT INTO payroll_reset_audits(payroll_period_id,employee_payroll_record_id,payment_id,action,reason,actor_id,metadata) VALUES($1,$2,$3,$4,$5,$6,$7)",[input.periodId??null,input.recordId??null,input.paymentId??null,input.action,input.reason,input.actorId,JSON.stringify(input.metadata??{})]);}
async function resetRecord(c:PoolClient,record:any,reason:string,actorId:string,cleared:string[]){
 const payments=(await c.query("SELECT id,amount,payment_method,payment_date::text FROM payroll_payments WHERE payroll_record_id=$1 FOR UPDATE",[record.id])).rows;
 for(const payment of payments){await resetAudit(c,{periodId:record.payroll_period_id,recordId:record.id,paymentId:payment.id,action:"PAYMENT_RESET",reason,actorId,metadata:payment});await c.query("DELETE FROM payroll_payment_audit WHERE payroll_payment_id=$1",[payment.id]);await c.query("DELETE FROM payroll_payments WHERE id=$1",[payment.id]);}
 const slips=(await c.query("SELECT id,slip_number FROM payroll_slips WHERE employee_payroll_record_id=$1 FOR UPDATE",[record.id])).rows;
 for(const slip of slips){await resetAudit(c,{periodId:record.payroll_period_id,recordId:record.id,action:"SALARY_SLIP_RESET",reason,actorId,metadata:slip});}await c.query("DELETE FROM payroll_slips WHERE employee_payroll_record_id=$1",[record.id]);
 const repayment=(await c.query("SELECT id,employee_id,amount,transaction_date::text FROM employee_advance_transactions WHERE payroll_record_id=$1 FOR UPDATE",[record.id])).rows;
 for(const entry of repayment){await c.query("UPDATE employee_advance_transactions SET payroll_record_id=NULL,notes=concat(coalesce(notes,''),$2) WHERE id=$1",[entry.id," [Payroll reset: repayment reversed]"]);await c.query("INSERT INTO employee_advance_transactions(employee_id,transaction_type,amount,transaction_date,notes,created_by) VALUES($1,'ADJUSTMENT',$2,$3,$4,$5)",[entry.employee_id,entry.amount,entry.transaction_date,`Payroll reset reversal for repayment ${entry.id}`,actorId]);await resetAudit(c,{periodId:record.payroll_period_id,recordId:record.id,action:"ADVANCE_REPAYMENT_REVERSED",reason,actorId,metadata:entry});}
 const deductionCount=(await c.query("SELECT count(*)::int count FROM payroll_deductions WHERE payroll_record_id=$1",[record.id])).rows[0]?.count??0;
 await c.query("DELETE FROM payroll_deductions WHERE payroll_record_id=$1",[record.id]);
 await c.query("DELETE FROM payroll_adjustments WHERE payroll_record_id=$1",[record.id]);
 await resetAudit(c,{periodId:record.payroll_period_id,recordId:record.id,action:"PAYROLL_RECORD_RESET",reason,actorId,metadata:{employee_id:record.employee_id,deductions_removed:deductionCount}});
 await c.query("DELETE FROM employee_payroll_records WHERE id=$1",[record.id]);cleared.push(record.id);
}
async function removeEmptyResetPeriods(c:PoolClient,periodIds:string[],reason:string,actorId:string){const removed:string[]=[];for(const periodId of [...new Set(periodIds)]){const period=(await c.query("SELECT id,status FROM payroll_periods WHERE id=$1 FOR UPDATE",[periodId])).rows[0];if(!period)continue;const dependencies=(await c.query("SELECT (SELECT count(*)::int FROM employee_payroll_records WHERE payroll_period_id=$1) records,(SELECT count(*)::int FROM payroll_payments WHERE payroll_period_id=$1) payments,(SELECT count(*)::int FROM payroll_slips WHERE payroll_period_id=$1) slips",[periodId])).rows[0];if(Number(dependencies.records)+Number(dependencies.payments)+Number(dependencies.slips)>0)continue;await resetAudit(c,{periodId,action:"PAYROLL_PERIOD_RESET",reason,actorId,metadata:{previous_status:period.status}});await c.query("DELETE FROM payroll_periods WHERE id=$1",[periodId]);removed.push(periodId);}return removed;}
async function resetSelectedRecords(recordIds:string[],reason:string,actorId:string){const c=await pool.connect();try{await c.query("BEGIN");const records=(await c.query("SELECT id,payroll_period_id,employee_id FROM employee_payroll_records WHERE id=ANY($1::uuid[]) FOR UPDATE",[recordIds])).rows;const found=new Set(records.map((record:any)=>record.id));const cleared:string[]=[];for(const record of records)await resetRecord(c,record,reason,actorId,cleared);const periods=await removeEmptyResetPeriods(c,records.map((record:any)=>record.payroll_period_id),reason,actorId);await c.query("COMMIT");return {cleared:cleared.length,cleared_ids:cleared,skipped:recordIds.filter(id=>!found.has(id)),blocked:[],removed_period_ids:periods} as ResetSummary&{removed_period_ids:string[]};}catch(e){await c.query("ROLLBACK");throw e;}finally{c.release();}}
export async function resetPeriods(ids:string[],reason:string,actorId:string){const c=await pool.connect();try{await c.query("BEGIN");const periods=(await c.query("SELECT id FROM payroll_periods WHERE id=ANY($1::uuid[]) FOR UPDATE",[ids])).rows;const found=new Set(periods.map((period:any)=>period.id));const records=(await c.query("SELECT id,payroll_period_id,employee_id FROM employee_payroll_records WHERE payroll_period_id=ANY($1::uuid[]) FOR UPDATE",[periods.map((period:any)=>period.id)])).rows;const cleared:string[]=[];for(const record of records)await resetRecord(c,record,reason,actorId,cleared);const removed=await removeEmptyResetPeriods(c,periods.map((period:any)=>period.id),reason,actorId);await c.query("COMMIT");return {cleared:removed.length,cleared_ids:removed,skipped:ids.filter(id=>!found.has(id)),blocked:[],reset_record_ids:cleared} as ResetSummary&{reset_record_ids:string[]};}catch(e){await c.query("ROLLBACK");throw e;}finally{c.release();}}
export async function resetRecords(ids:string[],reason:string,actorId:string){return resetSelectedRecords(ids,reason,actorId);}
export async function resetPayments(ids:string[],reason:string,actorId:string){const payments=(await pool.query("SELECT id,payroll_record_id FROM payroll_payments WHERE id=ANY($1::uuid[])",[ids])).rows;const found=new Set(payments.map((payment:any)=>payment.id));const result=await resetSelectedRecords(payments.map((payment:any)=>payment.payroll_record_id),reason,actorId);return {...result,cleared:payments.length,cleared_ids:payments.map((payment:any)=>payment.id),skipped:ids.filter(id=>!found.has(id))};}
