import { Router } from "express";
import { requireAuth, requireRole } from "../auth/auth.middleware.js";
import * as controller from "./payroll.controller.js";
import { requirePayrollEnabled } from "./payroll.guard.js";

const router = Router();
router.use(requireAuth);
router.get("/periods", requireRole("ADMIN", "MANAGER"), controller.listPeriods);
router.get("/periods/:id", requireRole("ADMIN", "MANAGER"), controller.getPeriod);
router.delete("/periods/bulk-drafts", requireRole("ADMIN"), requirePayrollEnabled, controller.deleteDrafts);
router.delete("/periods/bulk-empty-cancelled", requireRole("ADMIN"), requirePayrollEnabled, controller.deleteEmptyCancelled);
router.delete("/periods/bulk-clear-test", requireRole("ADMIN"), requirePayrollEnabled, controller.clearUnpaidTestPeriods);
router.delete("/periods/bulk-reset", requireRole("ADMIN"), requirePayrollEnabled, controller.resetPeriods);
router.post("/periods", requireRole("ADMIN", "MANAGER"), requirePayrollEnabled, controller.createPeriod);
router.post("/periods/:id/replacement", requireRole("ADMIN"), requirePayrollEnabled, controller.createReplacement);
router.post("/periods/:id/generate", requireRole("ADMIN", "MANAGER"), requirePayrollEnabled, controller.generate);
router.post("/periods/:id/recalculate", requireRole("ADMIN", "MANAGER"), requirePayrollEnabled, controller.recalculate);
router.post("/periods/:id/approve", requireRole("ADMIN"), requirePayrollEnabled, controller.approve);
router.post("/periods/:id/pay", requireRole("ADMIN"), requirePayrollEnabled, controller.pay);
router.post("/periods/:id/lock", requireRole("ADMIN"), requirePayrollEnabled, controller.lock);
router.post("/periods/:id/cancel", requireRole("ADMIN"), requirePayrollEnabled, controller.cancel);
router.get("/periods/:id/records", requireRole("ADMIN", "MANAGER"), controller.listRecords);
router.get("/periods/:id/payments", requireRole("ADMIN", "MANAGER"), controller.listPeriodPayments);
router.get("/periods/:id/slips", requireRole("ADMIN", "MANAGER"), controller.listSlips);
router.get("/records/:recordId", requireRole("ADMIN", "MANAGER"), controller.getRecord);
router.get("/records/:recordId/payments", requireRole("ADMIN", "MANAGER"), controller.listRecordPayments);
router.get("/records/:recordId/slip", requireRole("ADMIN", "MANAGER"), controller.getSlip);
router.get("/records/:recordId/slip/pdf", requireRole("ADMIN", "MANAGER"), controller.getSlipPdf);
router.delete("/records/bulk-reset", requireRole("ADMIN"), requirePayrollEnabled, controller.resetRecords);
router.delete("/payments/bulk-reset", requireRole("ADMIN"), requirePayrollEnabled, controller.resetPayments);
router.post("/payments/:paymentId/reverse", requireRole("ADMIN"), requirePayrollEnabled, controller.reversePayment);
router.patch("/records/:recordId", requireRole("ADMIN", "MANAGER"), requirePayrollEnabled, controller.updateRecord);
router.patch("/records/:recordId/status", requireRole("ADMIN", "MANAGER"), requirePayrollEnabled, controller.updateRecordStatus);
router.post("/records/:recordId/deductions", requireRole("ADMIN", "MANAGER"), requirePayrollEnabled, controller.addDeduction);
router.patch("/records/:recordId/deductions/:deductionId", requireRole("ADMIN", "MANAGER"), requirePayrollEnabled, controller.updateDeduction);
router.delete("/records/:recordId/deductions/:deductionId", requireRole("ADMIN", "MANAGER"), requirePayrollEnabled, controller.deleteDeduction);
export default router;
