/* eslint-disable @typescript-eslint/no-explicit-any */
import { getDatabasePool } from "../../infrastructure/database/database.js";
const pool=getDatabasePool();
const money=(n:number)=>Math.round((n+Number.EPSILON)*100)/100;
const n=(v:unknown)=>Number(v??0);
function immutable(period:{status:string}, record?:{status:string}) { if(period.status==="LOCKED"||period.status==="CANCELLED"||record?.status==="PAID"||record?.status==="CANCELLED") throw new Error("Validation: This payroll record is read-only"); }

export async function listPeriods(){return (await pool.query(`SELECT p.*,count(r.id)::int employee_count,coalesce(sum(r.gross_pay),0) gross_total,coalesce(sum(r.attendance_deduction+r.other_deductions),0) deduction_total,coalesce(sum(r.advance_recovery),0) advance_recovery_total,coalesce(sum(r.net_pay),0) net_pay_total FROM payroll_periods p LEFT JOIN employee_payroll_records r ON r.payroll_period_id=p.id GROUP BY p.id ORDER BY year DESC,month DESC,p.created_at DESC`)).rows;}
export async function getPeriod(id:string){const r=await pool.query("SELECT id,year,month,period_start::text AS period_start,period_end::text AS period_end,status,generated_at,generated_by,locked_at,locked_by,notes,cancellation_reason,created_at,updated_at FROM payroll_periods WHERE id=$1",[id]);if(!r.rows[0])throw new Error("Not Found: Payroll period not found");return r.rows[0];}
export async function createPeriod(input:{year?:number;month?:number;notes?:string}, userId:string){const year=Number(input.year),month=Number(input.month);if(!Number.isInteger(year)||!Number.isInteger(month)||month<1||month>12)throw new Error("Validation: A valid year and month are required");const active=await pool.query("SELECT 1 FROM payroll_periods WHERE year=$1 AND month=$2 AND status <> 'CANCELLED' LIMIT 1",[year,month]);if(active.rowCount)throw new Error("Conflict: A payroll period already exists for this month");const start=`${year}-${String(month).padStart(2,"0")}-01`;const end=new Date(Date.UTC(year,month,0)).toISOString().slice(0,10);try{return (await pool.query("INSERT INTO payroll_periods(year,month,period_start,period_end,notes,generated_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,year,month,period_start::text AS period_start,period_end::text AS period_end,status,generated_at,generated_by,locked_at,locked_by,notes,cancellation_reason,created_at,updated_at",[year,month,start,end,input.notes??null,userId])).rows[0];}catch(e){if((e as {code?:string}).code==="23505")throw new Error("Conflict: A payroll period already exists for this month");throw e;}}

async function period(id:string){return getPeriod(id) as Promise<{id:string;period_start:string;period_end:string;status:string}>;}
async function deductions(recordId:string){return (await pool.query("SELECT * FROM payroll_deductions WHERE payroll_record_id=$1 ORDER BY created_at",[recordId])).rows;}
async function recalcRecord(p:{id:string;period_start:string;period_end:string;status:string}, employee:{id:string;joining_date:string|null}, salary:any, existing:any){
 const attendance=(await pool.query(`SELECT status,count(*)::int count,coalesce(sum(working_minutes),0)::int work FROM daily_attendance_records WHERE employee_id=$1 AND attendance_date BETWEEN $2 AND $3 GROUP BY status`,[employee.id,p.period_start,p.period_end])).rows;
 const counts:Record<string,number>={};let work=0; for(const a of attendance){counts[a.status]=n(a.count??1);work+=n(a.work);}
 // Query rows rather than raw punches; missing calendar dates are treated as absence only within employment/salary eligibility.
 const joined=employee.joining_date&&employee.joining_date>p.period_start?employee.joining_date:p.period_start;
 const calendar=Math.floor((Date.parse(`${p.period_end}T00:00:00Z`)-Date.parse(`${joined}T00:00:00Z`))/86400000)+1;
 const present=(counts.PRESENT??0),late=(counts.LATE??0),early=(counts.EARLY_EXIT??0),lateEarly=(counts.LATE_AND_EARLY_EXIT??0),half=(counts.HALF_DAY??0),weekly=(counts.WEEKLY_OFF??0),holiday=(counts.HOLIDAY??0),missing=(counts.MISSING_PUNCH??0),noShift=(counts.NO_SHIFT??0),unmatched=(counts.UNMATCHED??0);
 const recorded=present+late+early+lateEarly+half+weekly+holiday+missing+noShift+unmatched+(counts.ABSENT??0); const absent=Math.max(counts.ABSENT??0,Math.max(0,calendar-recorded)); const payable=present+late+early+lateEarly+half*.5+weekly+holiday;
 const base=n(salary.monthly_salary??salary.daily_rate??salary.hourly_rate); let attendanceDeduction=0,gross=0;
 if(salary.salary_type==="MONTHLY"){const daily=base/(new Date(Date.UTC(Number(p.period_start.slice(0,4)),Number(p.period_start.slice(5,7)),0)).getUTCDate());attendanceDeduction=money(daily*Math.max(0,calendar-payable));gross=money(Math.max(0,base-attendanceDeduction));}
 if(salary.salary_type==="DAILY")gross=money(payable*base);
 if(salary.salary_type==="HOURLY")gross=money((work/60)*base);
 const ds=existing?await deductions(existing.id):[]; const other=money(ds.reduce((s,d)=>s+n(d.amount),0)); const recovery=n(existing?.advance_recovery); const net=money(Math.max(0,gross-other-recovery)); const details={method:"calendar-day proration",calendar_days:new Date(Date.UTC(Number(p.period_start.slice(0,4)),Number(p.period_start.slice(5,7)),0)).getUTCDate(),eligible_employment_days:calendar,payable_day_equivalent:payable,total_work_minutes:work,early_exit_days:early,late_and_early_exit_days:lateEarly,no_shift_days:noShift,unmatched_days:unmatched,unpaid_balance:money(Math.max(0,other+recovery-gross))};
 const vals=[p.id,employee.id,salary.id,salary.salary_type,money(base),payable,present,late,half,absent,weekly,holiday,missing,work,attendanceDeduction,other,recovery,gross,net,JSON.stringify(details)];
 if(existing) return (await pool.query(`UPDATE employee_payroll_records SET salary_history_id=$3,salary_type=$4,base_salary=$5,payable_days=$6,present_days=$7,late_days=$8,half_days=$9,absent_days=$10,weekly_off_days=$11,holiday_days=$12,missing_punch_days=$13,total_work_minutes=$14,attendance_deduction=$15,other_deductions=$16,advance_recovery=$17,gross_pay=$18,net_pay=$19,calculation_details=$20 WHERE id=$21 RETURNING *`,[...vals,existing.id])).rows[0];
 return (await pool.query(`INSERT INTO employee_payroll_records(payroll_period_id,employee_id,salary_history_id,salary_type,base_salary,payable_days,present_days,late_days,half_days,absent_days,weekly_off_days,holiday_days,missing_punch_days,total_work_minutes,attendance_deduction,other_deductions,advance_recovery,gross_pay,net_pay,calculation_details) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20) RETURNING *`,vals)).rows[0];
}
export async function generate(id:string,userId:string){const p=await period(id);if(p.status==="LOCKED"||p.status==="CANCELLED")throw new Error("Validation: This payroll period cannot be generated");const employees=(await pool.query("SELECT id,joining_date::text FROM employees WHERE joining_date IS NULL OR joining_date <= $1",[p.period_end])).rows;let created=0,updated=0;const skipped:string[]=[];for(const e of employees){const salary=(await pool.query("SELECT * FROM employee_salary_history WHERE employee_id=$1 AND active AND effective_from <= $3::date AND (effective_to IS NULL OR effective_to >= $2::date) ORDER BY effective_from DESC LIMIT 1",[e.id,p.period_start,p.period_end])).rows[0];if(!salary){skipped.push(e.id);continue;}const existing=(await pool.query("SELECT * FROM employee_payroll_records WHERE payroll_period_id=$1 AND employee_id=$2",[id,e.id])).rows[0];if(existing) { if(existing.status!=="PAID"&&existing.status!=="CANCELLED") updated++; continue; }await recalcRecord(p,e,salary,existing);created++;}await pool.query("UPDATE payroll_periods SET status='GENERATED',generated_at=coalesce(generated_at,now()),generated_by=$2 WHERE id=$1",[id,userId]);return {created,updated,skipped_employee_ids:skipped};}
export async function recalculate(id:string,userId:string){const p=await period(id);if(p.status==="LOCKED"||p.status==="CANCELLED")throw new Error("Validation: This payroll period cannot be recalculated");return generate(id,userId);}
export async function listRecords(id:string){await period(id);return (await pool.query(`SELECT r.*,e.name employee_name,e.biometric_id FROM employee_payroll_records r JOIN employees e ON e.id=r.employee_id WHERE r.payroll_period_id=$1 ORDER BY e.name`,[id])).rows;}
export async function getRecord(id:string){const r=await pool.query(`SELECT r.*,p.status period_status,p.period_end::text,e.name employee_name,e.biometric_id,s.effective_from::text salary_effective_from,s.effective_to::text salary_effective_to FROM employee_payroll_records r JOIN payroll_periods p ON p.id=r.payroll_period_id JOIN employees e ON e.id=r.employee_id JOIN employee_salary_history s ON s.id=r.salary_history_id WHERE r.id=$1`,[id]);if(!r.rows[0])throw new Error("Not Found: Payroll record not found");return {...r.rows[0],deductions:await deductions(id)};}
export async function updateRecord(id:string,input:{advance_recovery?:number}){const r:any=await getRecord(id);immutable({status:r.period_status},r);if(input.advance_recovery===undefined)throw new Error("Validation: advance_recovery is required");const recovery=money(Number(input.advance_recovery));if(!Number.isFinite(recovery)||recovery<0)throw new Error("Validation: Advance recovery must be non-negative");const balance=n((await pool.query(`SELECT coalesce(sum(CASE WHEN transaction_type IN ('OPENING_ADVANCE','ADVANCE_GIVEN','ADJUSTMENT') THEN amount ELSE -amount END),0) balance FROM employee_advance_transactions WHERE employee_id=$1`,[r.employee_id])).rows[0].balance);if(recovery>balance)throw new Error("Validation: Advance recovery cannot exceed the pending advance balance");if(recovery>n(r.gross_pay)-n(r.other_deductions))throw new Error("Validation: Advance recovery cannot make net pay negative");return (await pool.query("UPDATE employee_payroll_records SET advance_recovery=$2,net_pay=$3 WHERE id=$1 RETURNING *",[id,recovery,money(n(r.gross_pay)-n(r.other_deductions)-recovery)])).rows[0];}
export async function updateRecordStatus(id:string,status:string,userId:string,role:string){const r:any=await getRecord(id);immutable({status:r.period_status},r);if(!["DRAFT","APPROVED","PAID","CANCELLED"].includes(status))throw new Error("Validation: Invalid payroll record status");if(status==="PAID"&&role!=="ADMIN")throw new Error("Validation: Only ADMIN can mark payroll records PAID");if(status==="PAID")await repay(r,userId);return (await pool.query("UPDATE employee_payroll_records SET status=$2 WHERE id=$1 RETURNING *",[id,status])).rows[0];}
async function assertEditable(id:string){const r:any=await getRecord(id);immutable({status:r.period_status},r);return r;}
async function refreshTotals(id:string){const r:any=await getRecord(id);const other=money((await deductions(id)).reduce((s,d)=>s+n(d.amount),0));await pool.query("UPDATE employee_payroll_records SET other_deductions=$2,net_pay=$3 WHERE id=$1",[id,other,money(Math.max(0,n(r.gross_pay)-other-n(r.advance_recovery)))]);}
export async function addDeduction(id:string,input:any){await assertEditable(id);const amount=money(Number(input.amount));if(!["OTHER","DAMAGE","LOAN","PENALTY"].includes(input.deduction_type)||amount<=0)throw new Error("Validation: Valid positive deduction is required");const d=(await pool.query("INSERT INTO payroll_deductions(payroll_record_id,deduction_type,amount,notes) VALUES($1,$2,$3,$4) RETURNING *",[id,input.deduction_type,amount,input.notes??null])).rows[0];await refreshTotals(id);return d;}
export async function updateDeduction(id:string,did:string,input:any){await assertEditable(id);const amount=input.amount===undefined?undefined:money(Number(input.amount));if(amount!==undefined&&amount<=0)throw new Error("Validation: Deduction amount must be positive");const d=(await pool.query("UPDATE payroll_deductions SET deduction_type=coalesce($3,deduction_type),amount=coalesce($4,amount),notes=CASE WHEN $5 THEN $6 ELSE notes END WHERE id=$2 AND payroll_record_id=$1 RETURNING *",[id,did,input.deduction_type??null,amount??null,input.notes!==undefined,input.notes??null])).rows[0];if(!d)throw new Error("Not Found: Deduction not found");await refreshTotals(id);return d;}
export async function deleteDeduction(id:string,did:string){await assertEditable(id);const d=await pool.query("DELETE FROM payroll_deductions WHERE id=$2 AND payroll_record_id=$1 RETURNING id",[id,did]);if(!d.rows[0])throw new Error("Not Found: Deduction not found");await refreshTotals(id);}
async function repay(r:any,userId:string){if(n(r.advance_recovery)<=0)return;await pool.query("INSERT INTO employee_advance_transactions(employee_id,transaction_type,amount,transaction_date,notes,created_by,payroll_record_id) VALUES($1,'REPAYMENT',$2,$3,$4,$5,$6) ON CONFLICT (payroll_record_id) WHERE payroll_record_id IS NOT NULL DO NOTHING",[r.employee_id,r.advance_recovery,r.period_end,`Payroll recovery for period ${r.payroll_period_id}`,userId,r.id]);}
export async function lock(id:string,userId:string){const p:any=await period(id);if(p.status==="LOCKED")return p;if(p.status==="CANCELLED")throw new Error("Validation: Cancelled payroll cannot be locked");const records=await listRecords(id);for(const r of records){if(r.status!=="CANCELLED")await repay({...r,period_end:p.period_end},userId);}return (await pool.query("UPDATE payroll_periods SET status='LOCKED',locked_at=now(),locked_by=$2 WHERE id=$1 RETURNING *",[id,userId])).rows[0];}
export async function cancel(id:string,cancellationReason?:string){const p:any=await period(id);if(p.status==="LOCKED")throw new Error("Validation: A locked payroll period cannot be cancelled");if(p.status==="CANCELLED")return p;return (await pool.query("UPDATE payroll_periods SET status='CANCELLED',cancellation_reason=$2 WHERE id=$1 RETURNING *",[id,cancellationReason?.trim()||null])).rows[0];}
export async function deleteDrafts(ids:string[]){if(!ids.length)throw new Error("Validation: Select at least one draft payroll period");const c=await pool.connect();try{await c.query("BEGIN");const invalid=await c.query("SELECT p.id FROM payroll_periods p WHERE p.id=ANY($1::uuid[]) AND (p.status<>'DRAFT' OR p.generated_at IS NOT NULL OR EXISTS(SELECT 1 FROM employee_payroll_records r WHERE r.payroll_period_id=p.id))",[ids]);if(invalid.rowCount)throw new Error("Conflict: Only unused DRAFT payroll periods can be deleted");const result=await c.query("DELETE FROM payroll_periods WHERE id=ANY($1::uuid[]) RETURNING id",[ids]);await c.query("COMMIT");return{deleted:result.rowCount??0};}catch(e){await c.query("ROLLBACK");throw e;}finally{c.release();}}
