import type { NextFunction, Request, Response } from "express";
import { createAdvanceSchema, updateAdvanceSchema } from "./advances.schema.js";
import * as service from "./advances.service.js";

function sendError(res: Response, error: unknown): void { const message=error instanceof Error?error.message:"Advance operation failed"; if(message.startsWith("Not Found:")){res.status(404).json({message:message.slice(11)});return;} if(message.startsWith("Conflict:")){res.status(409).json({message});return;} res.status(400).json({message}); }
export async function listAdvances(req: Request,res:Response,next:NextFunction):Promise<void>{try{res.json(await service.listAdvances(req.params.employeeId as string));}catch(error){if(error instanceof Error&&error.message.startsWith("Not Found:"))sendError(res,error);else next(error);}}
export async function getBalance(req: Request,res:Response,next:NextFunction):Promise<void>{try{res.json(await service.getBalance(req.params.employeeId as string));}catch(error){if(error instanceof Error&&error.message.startsWith("Not Found:"))sendError(res,error);else next(error);}}
export async function createAdvance(req: Request,res:Response):Promise<void>{const parsed=createAdvanceSchema.safeParse(req.body);if(!parsed.success){res.status(400).json({message:"Validation failed",errors:parsed.error.issues});return;}try{res.status(201).json(await service.createAdvance(req.params.employeeId as string,req.user!.id,parsed.data));}catch(error){sendError(res,error);}}
export async function updateAdvance(req: Request,res:Response):Promise<void>{const parsed=updateAdvanceSchema.safeParse(req.body);if(!parsed.success){res.status(400).json({message:"Validation failed",errors:parsed.error.issues});return;}try{const updated=await service.updateAdvance(req.params.employeeId as string,req.params.transactionId as string,parsed.data);if(!updated){res.status(404).json({message:"Advance transaction not found"});return;}res.json(updated);}catch(error){sendError(res,error);}}
