import { Buffer } from "node:buffer";
import type { Request, Response } from "express";
import PDFDocument from "pdfkit";
import * as reports from "./reports.service.js";
import type { ReportName } from "./reports.service.js";

const names = new Set<ReportName>(["attendance-summary", "payroll-summary", "salary-history", "advances", "device-logs", "raw-punches", "attendance-exceptions", "unmatched-biometrics"]);
const financial = /(?:salary|pay|deduction|recovery|amount|balance|additions|gross|net)/iu;
function name(req: Request): ReportName { const value=req.params.report as ReportName; if(!names.has(value)) throw new Error("Not Found: report"); return value; }
function error(res:Response,e:unknown) { const text=e instanceof Error?e.message:"Report failed"; res.status(text.startsWith("Not Found")?404:400).json({message:text.replace(/^Validation: /u,"")}); }
function csv(rows:Record<string,unknown>[]) { const keys=Object.keys(rows[0]??{}).filter(key=>key!=="employee_id"); const cell=(v:unknown)=>`"${String(v??"").replaceAll('"','""')}"`; return `\uFEFF${keys.join(',')}\r\n${rows.map(row=>keys.map(k=>cell(row[k])).join(',')).join('\r\n')}\r\n`; }
function label(key:string) { return key === "employee_code" ? "Employee ID" : key.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function minutes(raw:unknown){const value=Number(raw);if(!Number.isFinite(value))return "0m";const hours=Math.floor(value/60),rest=Math.abs(value%60);return hours?`${hours}h ${String(rest).padStart(2,"0")}m`:`${rest}m`;}
function value(key:string, raw:unknown) { if (raw === null || raw === undefined) return "—"; if (typeof raw === "boolean") return raw ? "Active" : "Inactive"; if (/(?:minutes|overtime)/iu.test(key) && /^-?\d+(\.\d+)?$/u.test(String(raw))) return minutes(raw); if (financial.test(key) && /^-?\d+(\.\d+)?$/u.test(String(raw))) return `₹${new Intl.NumberFormat("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(Number(raw))}`; return String(raw).replaceAll("_", " "); }
function filterText(query:Request["query"]) { const selected=Object.entries(query).filter(([key,value])=>!['page','limit'].includes(key)&&typeof value==='string'&&value).map(([key,value])=>`${label(key)}: ${value}`); return selected.length ? selected.join(" • ") : "All records"; }
function pdf(title:string, rows:Record<string,unknown>[], query:Request["query"]) {
  const document=new PDFDocument({layout:"landscape",size:"A4",margin:30,bufferPages:true});const chunks:Buffer[]=[];document.on("data",(chunk:Buffer)=>chunks.push(chunk));const columns=Object.keys(rows[0]??{}).filter(key=>key!=="employee_id");const left=30,right=30,width=(document.page.width-left-right)/Math.max(1,columns.length),generated=new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Kolkata"}).format(new Date());let y=0;
  const header=()=>{document.font("Helvetica-Bold").fontSize(12).fillColor("#12304A").text("RANJI RAMS HOTEL",left,28);document.fontSize(8).text("Hotel Management System",left,44);document.fontSize(11).text(`${title} Report`,left,57);document.font("Helvetica").fontSize(7).fillColor("#444").text(`Filters: ${filterText(query)}`,left,73,{width:document.page.width-left-right});document.text(`Generated (IST): ${generated}`,left,84);document.moveTo(left,97).lineTo(document.page.width-right,97).strokeColor("#2C5D7B").stroke();let x=left;document.fillColor("#12304A").font("Helvetica-Bold").fontSize(6.5);columns.forEach(column=>{document.text(label(column),x,104,{width:width-3,height:14,ellipsis:true});x+=width;});document.moveTo(left,120).lineTo(document.page.width-right,120).strokeColor("#999").stroke();document.font("Helvetica").fillColor("#111");y=124;};header();
  if(!rows.length)document.text("No matching records.",left,y);for(const row of rows){const cells=columns.map(column=>value(column,row[column]));const height=Math.max(18,...cells.map(cell=>document.heightOfString(cell,{width:width-4})))+6;if(y+height>document.page.height-38){document.addPage();header();}let x=left;cells.forEach((cell,index)=>{document.text(cell,x,y+3,{width:width-4,height:height-4,align:/(?:minutes|days|count|amount|salary|pay|balance)/iu.test(columns[index]!)?"right":"left"});x+=width;});document.moveTo(left,y+height).lineTo(document.page.width-right,y+height).strokeColor("#ddd").stroke();y+=height;}
  const range=document.bufferedPageRange();for(let page=0;page<range.count;page+=1){document.switchToPage(page);document.fillColor("#444").fontSize(7).text(`RANJI RAMS HOTEL • Page ${page+1} of ${range.count}`,left,document.page.height-24,{width:document.page.width-left-right,align:"right"});}document.end();return new Promise<Buffer>((resolve,reject)=>{document.on("end",()=>resolve(Buffer.concat(chunks)));document.on("error",reject);});
}
export async function get(req:Request,res:Response){try{res.json(await reports.report(name(req),req.query));}catch(e){error(res,e)}}
export async function exportReport(req:Request,res:Response){try{const report=await reports.report(name(req),{...req.query,page:1,limit:100});const title=name(req).replaceAll('-',' ');if(req.params.format==='csv')res.type('text/csv; charset=utf-8').attachment(`${name(req)}.csv`).send(csv(report.items as Record<string,unknown>[]));else res.type('application/pdf').set('Content-Disposition',`inline; filename=${name(req)}.pdf`).send(await pdf(title,report.items as Record<string,unknown>[],req.query));}catch(e){error(res,e)}}

export async function getEmployeeAttendance(req:Request,res:Response){try{res.json(await reports.employeeAttendanceDetail(String(req.params.employeeId??''),req.query));}catch(e){error(res,e)}}
export async function exportEmployeeAttendance(req:Request,res:Response){try{const empId=String(req.params.employeeId??'');const data=await reports.employeeAttendanceDetail(empId,{...req.query,page:1,limit:366});const emp=data.employee as Record<string,unknown>;const title=`Attendance Report – ${String(emp.name??'')}`;if(req.params.format==='csv')res.type('text/csv; charset=utf-8').attachment(`attendance-${empId}.csv`).send(csv(data.items as Record<string,unknown>[]));else res.type('application/pdf').set('Content-Disposition',`inline; filename=attendance-${empId}.pdf`).send(await pdf(title,data.items as Record<string,unknown>[],req.query));}catch(e){error(res,e)}}
