import { Buffer } from "node:buffer";
import type { Request, Response } from "express";
import PDFDocument from "pdfkit";
import * as reports from "./reports.service.js";
import type { ReportName } from "./reports.service.js";

const names = new Set<ReportName>(["attendance-summary", "payroll-summary", "salary-history", "advances", "device-logs", "raw-punches", "attendance-exceptions"]);
const financial = /(?:salary|pay|deduction|recovery|amount|balance|total|additions)/iu;
function name(req: Request): ReportName { const value=req.params.report as ReportName; if(!names.has(value)) throw new Error("Not Found: report"); return value; }
function error(res:Response,e:unknown) { const text=e instanceof Error?e.message:"Report failed"; res.status(text.startsWith("Not Found")?404:400).json({message:text.replace(/^Validation: /u,"")}); }
function csv(rows:Record<string,unknown>[]) { const keys=Object.keys(rows[0]??{}); const cell=(v:unknown)=>`"${String(v??"").replaceAll('"','""')}"`; return `\uFEFF${keys.join(',')}\r\n${rows.map(row=>keys.map(k=>cell(row[k])).join(',')).join('\r\n')}\r\n`; }
function label(key:string) { return key.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function value(key:string, raw:unknown) { if (raw === null || raw === undefined) return "—"; if (typeof raw === "boolean") return raw ? "Active" : "Inactive"; if (financial.test(key) && /^-?\d+(\.\d+)?$/u.test(String(raw))) return `Rs. ${new Intl.NumberFormat("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(Number(raw))}`; return String(raw).replaceAll("_", " "); }
function filterText(query:Request["query"]) { const selected=Object.entries(query).filter(([key,value])=>!['page','limit'].includes(key)&&typeof value==='string'&&value).map(([key,value])=>`${label(key)}: ${value}`); return selected.length ? selected.join(" • ") : "All records"; }
function pdf(title:string, rows:Record<string,unknown>[], query:Request["query"]) {
  const document = new PDFDocument({ layout: "landscape", size: "A4", margin: 30, bufferPages: true }); const chunks:Buffer[]=[]; document.on("data",(chunk:Buffer)=>chunks.push(chunk));
  const columns=Object.keys(rows[0]??{}); const rowsPerPage=16; const pages=Math.max(1,Math.ceil(rows.length/rowsPerPage)); const generated=new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Kolkata"}).format(new Date()); const width=(document.page.width-document.page.margins.left-document.page.margins.right)/Math.max(columns.length,1);
  const drawHeader=(page:number)=>{ const left=document.page.margins.left; document.font("Helvetica-Bold").fontSize(12).fillColor("#12304A").text("RANJI RAMS HOTEL",left,28); document.fontSize(8).text("Hotel Management System",left,45); document.fontSize(11).text(`${title} Report`,left,58); document.font("Helvetica").fontSize(7).fillColor("#444").text(`Filters: ${filterText(query)}`,left,74,{width:document.page.width-left*2,ellipsis:true}); document.text(`Generated (IST): ${generated}`,left,85); document.moveTo(left,98).lineTo(document.page.width-left,98).strokeColor("#2C5D7B").stroke(); document.fillColor("#12304A"); let x=left; const y=105; document.font("Helvetica-Bold").fontSize(6.5); columns.forEach((column)=>{document.text(label(column),x,y,{width:width-3,height:16,ellipsis:true});x+=width;}); document.moveTo(left,123).lineTo(document.page.width-left,123).strokeColor("#999").stroke(); document.fillColor("#111"); document.font("Helvetica").fontSize(6.5); document.text(`RANJI RAMS HOTEL • Page ${page} of ${pages}`,document.page.width-left-120,document.page.height-24,{width:120,align:"right"}); };
  for(let page=0;page<pages;page+=1){if(page)document.addPage();drawHeader(page+1);const pageRows=rows.slice(page*rowsPerPage,(page+1)*rowsPerPage);if(!pageRows.length)document.text("No matching records.",document.page.margins.left,122);pageRows.forEach((row,index)=>{const y=118+index*34;let x=document.page.margins.left;columns.forEach((column)=>{document.text(value(column,row[column]),x,y,{width:width-3,height:28,ellipsis:true});x+=width;});document.moveTo(document.page.margins.left,y+30).lineTo(document.page.width-document.page.margins.left,y+30).strokeColor("#ddd").stroke();document.fillColor("#111");});}
  document.end(); return new Promise<Buffer>((resolve,reject)=>{document.on("end",()=>resolve(Buffer.concat(chunks)));document.on("error",reject);});
}
export async function get(req:Request,res:Response){try{res.json(await reports.report(name(req),req.query));}catch(e){error(res,e)}}
export async function exportReport(req:Request,res:Response){try{const report=await reports.report(name(req),{...req.query,page:1,limit:100});const title=name(req).replaceAll('-',' ');if(req.params.format==='csv')res.type('text/csv; charset=utf-8').attachment(`${name(req)}.csv`).send(csv(report.items as Record<string,unknown>[]));else res.type('application/pdf').set('Content-Disposition',`inline; filename=${name(req)}.pdf`).send(await pdf(title,report.items as Record<string,unknown>[],req.query));}catch(e){error(res,e)}}
